const productItems = [
  {
    name: 'Bombay',
    price: '921.00',
    origin: 'Lithuania',
    owner: 'Gregory Pfeffer',
    email: 'Trenton_Luettgen@yahoo.com',
    id: '1',
  },
  {
    name: 'Kurilian Bobtail',
    price: '274.00',
    origin: 'Vanuatu',
    owner: 'Sergio Schmidt',
    email: 'Kelsi.Fadel@yahoo.com',
    id: '2',
  },
  {
    name: 'Somali',
    price: '719.00',
    origin: 'Nicaragua',
    owner: 'Jeannette Friesen',
    email: 'Tamia.Hodkiewicz13@hotmail.com',
    id: '3',
  },
  {
    name: 'Minskin',
    price: '515.00',
    origin: 'Peru',
    owner: 'Dolores Feeney IV',
    email: 'Esteban39@gmail.com',
    id: '4',
  },
  {
    name: 'Turkish Van',
    price: '925.00',
    origin: 'Palau',
    owner: 'Elvira Crona',
    email: 'Stewart.Denesik40@gmail.com',
    id: '5',
  },
  {
    name: 'Balinese',
    price: '226.00',
    origin: 'India',
    owner: 'Kenny Olson',
    email: 'Fredy_Gislason94@gmail.com',
    id: '6',
  },
  {
    name: 'Savannah',
    price: '693.00',
    origin: 'Uruguay',
    owner: 'Tami Reinger',
    email: 'Nels79@gmail.com',
    id: '7',
  },
  {
    name: 'Burmese',
    price: '476.00',
    origin: 'Grenada',
    owner: 'Bertha Pagac',
    email: 'Weston.Feeney@gmail.com',
    id: '8',
  },
  {
    name: 'Sokoke',
    price: '646.00',
    origin: 'Portugal',
    owner: 'Miss Janis Gislason',
    email: 'Camden23@hotmail.com',
    id: '9',
  },
  {
    name: 'LaPerm',
    price: '655.00',
    origin: 'New Caledonia',
    owner: 'Kelli Murray',
    email: 'Osbaldo.Farrell27@gmail.com',
    id: '10',
  },
  {
    name: 'Burmese',
    price: '20.00',
    origin: 'Central African Republic',
    owner: 'Mr. Ramona Hirthe',
    email: 'Jovan76@gmail.com',
    id: '11',
  },
  {
    name: 'Persian',
    price: '679.00',
    origin: 'Madagascar',
    owner: 'Amos Bode',
    email: 'Cristopher21@gmail.com',
    id: '12',
  },
  {
    name: 'Turkish Van',
    price: '292.00',
    origin: 'Cuba',
    owner: 'Kristopher Sporer DVM',
    email: 'Camden78@yahoo.com',
    id: '13',
  },
  {
    name: 'Somali',
    price: '193.00',
    origin: 'Saint Vincent and the Grenadines',
    owner: 'Evelyn Kreiger',
    email: 'Norbert37@gmail.com',
    id: '14',
  },
  {
    name: 'Maine Coon',
    price: '710.00',
    origin: 'Indonesia',
    owner: 'Manuel Jacobs',
    email: 'Luisa6@hotmail.com',
    id: '15',
  },
]
export default productItems
